INSERT INTO `respostes_incorrectes` (`resposta_incorrecta`, `id_pregunta`) VALUES 
('30 km/h', 1),
('70 km/h', 1),
('90 km/h', 1),
('Prohibició', 2),
('Obligació', 2),
('Informativa', 2),
('Llicència de conduir', 3),
('Certificat de conducció', 3),
('Permís temporal', 3),
('Prova pràctica', 4),
('Prova psicotècnica', 4),
('Prova de maniobres', 4),
('Accelerar', 5),
('Canviar de carril', 5),
('Seguir circulant', 5),
('Advertència', 6),
('Informativa', 6),
('Obligació', 6),
('Estacionar', 7),
('Reversa', 7),
('Avançar', 7),
('Per expressar frustració', 8),
('Per saludar', 8),
('Per tocar música', 8),
('Activar els llums d\'emergència', 9),
('Indicar una frenada', 9),
('Fer una parada', 9),
('Reduir la velocitat', 10),
('Seguir sense parar', 10),
('Fer una maniobra', 10),
('Demostrar coneixements teòrics', 11),
('Fer una maniobra de canvi de direcció', 11),
('Aparcar correctament', 11),
('Seguir endavant', 12),
('Accelerar', 12),
('Canviar de carril sense senyalitzar', 12),
('Mantenir el conductor en la seva posició', 13),
('Evitar que el cotxe es mogui', 13),
('Assegurar el motor', 13),
('Sempre que ho necessitis', 14),
('Mai', 14),
('Quan estiguis aturat en un semàfor', 14);